### ISSUE TITLE
필수입력항목 ITEM_ID 관련 개선 의견

### ISSUE THREAD

**Issue by leeguembi** [dtonic/ess#12]
시스템 오류보다는 부수적인 개선 의견을 올립니다.

1. ITEM_ID는 필수항목 버튼으로 지정하지 않아도, 필수항목 처리됨. 필수항목 표시인 * 기호를 계속 표시하거나 항목관리에서 디폴트로 지정하는 것이 어떠할까요?
![image](https://user-images.githubusercontent.com/47589073/73507821-89829c00-441d-11ea-912b-0ec0e8f5df32.png)
<필수항목 표시 * 가 되어있지 않지만, 필수항목으로 표시되는 화면>

2. ESS 화면의 "새로운 상품" 항목으로 입력할 경우, ITEM_ID를 입력하지 않으면 업로드가 되지 않지만, 엑셀로 업로드할 때는 ITEM_ID 입력을 하지 않아도 업로드 가능한 것에 대해 개선 필요하지 않을까하는 의견 드립니다.
![image](https://user-images.githubusercontent.com/47589073/73507905-c8185680-441d-11ea-80c5-5ee268df7738.png)
<필수항목인 ITEM_ID 없이 업로드된 화면>

**Comment by rolla147** [comment]
향후 버전에서 수정하는 것이 좋을 것 같습니다. v2.0으로 넘겨 두겠습니다.
