### ISSUE TITLE
ITEM_ID 중복 입력 가능

### ISSUE THREAD

**Issue by nekonoyume** [dtonic/ess#17]
ITEM_ID가 중복되면 추후 문제가 발생할텐데, 중복 입력이 가능합니다.

**Comment by nekonoyume** [comment]
중복 입력이 가능하지만, 테이블업로드시 중복입력된 ITEM_ID가 있다면 계속 로딩 화면에 멈춰있습니다.

**Comment by LimDongGuk** [comment]
0.2.3 버전에서 Fix
