### ISSUE TITLE
ITEM_ID, DISPLAY TYPE 삭제 가능

### ISSUE THREAD

**Issue by nekonoyume** [dtonic/ess#19]
<작동경과>
1. 항목명이 ITEM_ID인 항목 추가
2. 기존 ITEM_ID항목 삭제
3, DISPLAY TYPE 삭제
4. 상품관리 -> 테이블 업로드 실행

결과 : 로딩 화면에 멈춰있음. 

![2](https://user-images.githubusercontent.com/48373603/73518104-c4e29200-4440-11ea-8c8d-54362d05a1a3.PNG)
![1](https://user-images.githubusercontent.com/48373603/73518105-c4e29200-4440-11ea-8c6b-63c10be9486e.PNG)

**Comment by LimDongGuk** [comment]
삭제 안되도록 변경
