### ISSUE TITLE
Java 미설치시 접속 불가

### ISSUE THREAD

**Issue by WhatsThisDog** [dtonic/ess#2]
타겟 pc내에 Java가 미설치되어 있을 시 접속주소(http://localhost:9090/)로 접속이 되지 않음

**Comment by dtonic** [comment]
설치 시 Java를 깔도록 되어 있습니다.
누구 PC인지 해당 PC의 Windows 버전을 알려주세요.
향후 설치 테스트 시 필요할 듯 합니다.

**Comment by DevJonathan90** [comment]
> 
> 
> 설치 시 Java를 깔도록 되어 있습니다.
> 누구 PC인지 해당 PC의 Windows 버전을 알려주세요.
> 향후 설치 테스트 시 필요할 듯 합니다.

JAVA 미설치 PC
- 이름 : Chloe, Ally
- Windows 버전 : Windows 10
- 설치 JAVA 버전 : 1.8.0_241
- 비고 : 해당 이슈는 어제 발생하였으며, JAVA 설치 이후 정상적으로 접속이 되는 것을 확인하였습니다.
