### ISSUE TITLE
공백인 항목에 대해 엑셀 다운로드시 값이 들어가있음

### ISSUE THREAD

**Issue by leeguembi** [dtonic/ess#21]
ESS 화면에서는 DISPLAY_TYPE과 DISPLAY_TYPE2 항목이 공백으로 되어있는데, 엑셀을 다운로드 하니, 항목명과 같은 내용으로 값이 들어가있음

![image](https://user-images.githubusercontent.com/47589073/73620062-841e8f00-4673-11ea-85b7-6eda408180b7.png)

![image](https://user-images.githubusercontent.com/47589073/73620133-c3e57680-4673-11ea-9be1-5d9636e49ffe.png)

**Comment by LimDongGuk** [comment]
에러 재현불가.
