### ISSUE TITLE
상품관리 탭의 엑셀 다운로드 정보 오류

### ISSUE THREAD

**Issue by DevJonathan90** [dtonic/ess#3]
상품관리 탭에서 기입력된 정보를 엑셀 파일로 다운로드 받아서 열어보면, Column 명을 제외하고 아무런 정보가 기재되어 있지 않음
![다운로드시 기입력된 정보 미표출](https://user-images.githubusercontent.com/46310302/73423615-fe979800-436f-11ea-9c1a-6fc20fa12cf1.JPG)

**Comment by leeguembi** [comment]
![image](https://user-images.githubusercontent.com/47589073/73506224-44a83680-4418-11ea-9079-3cdd1072c010.png)

![image](https://user-images.githubusercontent.com/47589073/73506205-39550b00-4418-11ea-9318-47d0f53fcb85.png)

- 상품관리 탭에 있는 정보에 대해 모두 정상적으로 입력된 엑셀 다운로드 확인 완료

**Comment by LimDongGuk** [comment]
0.2.3 버전에서 Fix
