### ISSUE TITLE
ESL 디스플레이 검은색 화면 표출

### ISSUE THREAD

**Issue by DevJonathan90** [dtonic/ess#4]
ESS 상에 필요한 정보를 업로드하고, 데이터가 정상적으로 처리된 것을 (시스템 상에서)확인하였으나,
ESL 디스플레이에서는 입력된 정보가 아닌 검은색 화면(어떤 문구였는지는 기억이 안남)이 표출됨

**Comment by rolla147** [comment]
제현이 가능한 상황이 필요합니다. 추가 해주세요.

**Comment by DevJonathan90** [comment]
> 
> 
> 제현이 가능한 상황이 필요합니다. 추가 해주세요.

![image](https://user-images.githubusercontent.com/46310302/73424727-073d9d80-4373-11ea-9267-750d9bd5b67a.png)
상기 이미지(Product Not Found)처럼 출력이 됩니다.

**Comment by rolla147** [comment]
이경우 제현을 해 보려면 올린 Excel 과 ESL ID도 필요합니다.

**Comment by LimDongGuk** [comment]
원인파악이되어 해결중인 이슈입니다.

**원인**
업로드한 데이터와 관계없이 ESL에 Item 정보를 등록완료한 다음에 Tag Assign을 해야하는데,
ESL Item등록 API에서 돌아오는 응답이 Item 정보 등록이 전부 완료되지 않은 상태에서 성공응답을 해버려 ESS가 Item이 등록이 완료된 상태로 인지해 Tag Assign로직을 수행하여 발생하는 이슈입니다.

**해결방법**
ESL API중 Item 정보를 조회하는 API를 활용하여 Item 등록이 완료된 Item만 Tag Assign로직을 수행하도록 변경중

**Comment by LimDongGuk** [comment]
0.2.3 버전에서 Fix
