### ISSUE TITLE
필수값으로 Field를 설정했음에도 빈칸 입력시 빈칸으로 데이터가 들어가는 현상 발생

### ISSUE THREAD

**Issue by JohnnyDaddy** [dtonic/ess#7]

**Comment by leeguembi** [comment]
수정 완료 확인.

- 필수항목의 경우, 빈칸 입력시 등록 불가 확인

![image](https://user-images.githubusercontent.com/47589073/73508149-76bc9700-441e-11ea-8235-44802d9c7def.png)

**Comment by LimDongGuk** [comment]
0.2.3 버전에서 Fix
