### ISSUE TITLE
설치시 JRE가 없을시 설치안되는 오류 발생

### ISSUE THREAD

**Issue by JohnnyDaddy** [dtonic/ess#8]

**Comment by rolla147** [comment]
오류를 캡처가 가능 할 까요?
윈도우 버전도 알려주세요. 
jre는 거의 기본으로 설치가 되어 있을터인데 왜 없을까요?

**Comment by JohnnyDaddy** [comment]
![image](https://user-images.githubusercontent.com/60460403/73425760-ff332d00-4375-11ea-9735-94bda63298ea.png)

windows 10 pro 입니다.

**Comment by rolla147** [comment]
설치는 되고 실행이 안되는 것으로 보입니다. 맞나요?

**Comment by JohnnyDaddy** [comment]
네 그런걸로 보입니다.
최초에는 서비스에 등록도 되지 않았다고 합니다.
