### ISSUE TITLE
항목 관리 삭제시 메세지 변경 필요. 상품 -->항목 

### ISSUE THREAD

**Issue by Ellenhatescucumber** [dtonic/ess#9]

**Comment by leeguembi** [comment]
![image](https://user-images.githubusercontent.com/47589073/73508053-2a715700-441e-11ea-8c5e-99a188380f7d.png)


항목관리에서 해당 항목을 삭제할때, 여전히 "상품"이라고 표시됩니다.
메세지 변경 필요. "상품->항목"
